server:
  port: 8181

spring:
  application:
    name: yte-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/yte_spring
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
